/**
	Generated by sails-inverse-model
	Date:Fri Jul 27 2018 15:53:08 GMT+0200 (CEST)
*/

module.exports = {
    attributes: {
        //  ╔═╗╦═╗╦╔╦╗╦╔╦╗╦╦  ╦╔═╗╔═╗
        //  ╠═╝╠╦╝║║║║║ ║ ║╚╗╔╝║╣ ╚═╗
        //  ╩  ╩╚═╩╩ ╩╩ ╩ ╩ ╚╝ ╚═╝╚═╝
        property_id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            allowNull: false
        },
        property_name: {
            type: Sequelize.STRING,
            allowNull: false
        },
        property_price: {
            type: Sequelize.INTEGER,
            allowNull: false
        },
        property_address: {
            type: Sequelize.STRING,
            allowNull: false
        },
        property_baths: {
            type: Sequelize.INTEGER,
            allowNull: false
        },
        property_beds: {
            type: Sequelize.INTEGER,
            allowNull: false
        },
        property_area: {
            type: Sequelize.STRING,
            allowNull: false
        },
        property_owner: {
            type: Sequelize.STRING,
            allowNull: false
        },
        property_image: {
            type: Sequelize.STRING,
            allowNull: true
        },
        property_description: {
            type: Sequelize.STRING,
            allowNull: true
        },

        //  ╔═╗╔╦╗╔╗ ╔═╗╔╦╗╔═╗
        //  ║╣ ║║║╠╩╗║╣  ║║╚═╗
        //  ╚═╝╩ ╩╚═╝╚═╝═╩╝╚═╝

    },
    associations: function() {
        //  ╔═╗╔═╗╔═╗╔═╗╔═╗╦╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
        //  ╠═╣╚═╗╚═╗║ ║║  ║╠═╣ ║ ║║ ║║║║╚═╗
        //  ╩ ╩╚═╝╚═╝╚═╝╚═╝╩╩ ╩ ╩ ╩╚═╝╝╚╝╚═╝
        // Property.belongsTo(User, { foreignKey: 'FK_user_id' });
    },
    defaultScope: function() {
        //  ╔═╗╔═╗╔═╗╔═╗╔═╗
        //  ╚═╗║  ║ ║╠═╝║╣
        //  ╚═╝╚═╝╚═╝╩  ╚═╝
        return {}
    },
    options: {
        tableName: 'tbl_property',
        classMethods: {},
        instanceMethods: {},
        hooks: {},
        scopes: {},
        timestamps: false,
        connection: 'default'
    }
};